In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

## Pauli Matrices

파울리 행렬의 아이겐밸류와 아이겐벡터를 구하시오.

$$ s_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}, \quad
s_y = \begin{pmatrix} 0 & -j \\ j & 0 \end{pmatrix}, \quad
s_z  = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix}. $$

In [12]:
sx = np.array([[0,1],
              [1,0]])
sy = np.array([[0,-1j],
               [1j,0]])
sz = np.array([[1,0],
               [0,-1]])

np.linalg.eig(sx), np.linalg.eig(sy), np.linalg.eig(sz)

((array([ 1., -1.]),
  array([[ 0.70710678, -0.70710678],
         [ 0.70710678,  0.70710678]])),
 (array([ 1.+0.j, -1.+0.j]),
  array([[-0.        -0.70710678j,  0.70710678+0.j        ],
         [ 0.70710678+0.j        ,  0.        -0.70710678j]])),
 (array([ 1., -1.]),
  array([[1., 0.],
         [0., 1.]])))

## Normal Modes

(고전역학 by Thornton & Marion 챕터 12.2 및 예제 12.3 참조) 용수철 상수가 $k$인 용수철에 연결된 두 개의 물체의 노말 모드를 구해보자. 두 개의 물체의 운동방정식은 다음으로 주어진다.$$ -m w^2 x_1 = -2kx_1 +k x_2, \\
-m w^2 x_2 = k x_1 - 2 k x_2.$$eigenfrequencies $w$는 다음의 행렬식을 통해 구할 수 있다.$$ \frac{k}{m w^2} \begin{pmatrix} 2 & -1 \\ -1 & 2 \end{pmatrix} 
\begin{pmatrix} x_1 \\ x_2 \end{pmatrix}=
\lambda \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} $$

In [13]:
m = np.array([[2,-1],
              [-1,2]])

np.linalg.eig(m)

(array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

따라서 eigenfrequencies는$$ w_1 = \sqrt{\frac{k}{m}}, \quad w_2 = \sqrt{\frac{3k}{m}}. $$

위에서 구한 아이겐벡터와 아이겐밸류의 의미를 설명하여라.

sol) 위에서 구한 답을 통해 eigenvalue, 즉 $\lambda$ 값이 3, 1인 것을 확인할 수 있다.
따라서 eigenfrequencies 식을 일반적으로 $ \omega=\sqrt{\frac{\lambda k}{m}}$ 으로 써줄 수 있다. (위 식에서는 이미 eigenvalue가 대입된 형태이다.) 이후 $\lambda$값을 대입해 $x_1$과 $x_2$의 비율(eigenvector)을 계산하면 물체의 노말모드 운동을 확인할 수 있다.

i) $\lambda=1$

$x_1$:$x_2$=$\sqrt{\frac{1}{2}}$:$\sqrt{\frac{1}{2}}$

$x_1$와 $x_2$의 값과 부호가 같음을 통해 두 개의 물체가 같은 크기와 같은 방향으로 운동한다는 것을 알 수 있다.


ii) $\lambda=3$

$x_1$:$x_2$=$\sqrt{\frac{1}{2}}$: -$\sqrt{\frac{1}{2}}$

$x_1$와 $x_2$가 값은 같지만 부호가 다름을 통해 두 개의 물체가 같은 크기와 반대 방향으로 운동한다는 것을 알 수 있다.

따라서 $w_1$는 입자 진동이 역위상이고, 입자속도가 같으나 반대방향인 것을 알 수 있고, $w_2$는 입자 진동이 같은 위상이고, 입자속도와 방향이 모두 같은 것을 알 수 있다.

결론적으로 eigenvector는 두 개의 물체의 운동의 크기와 방향을 나타내고, eigenvalue는 eigenfrequencies를 결정한다는 것을 확인할 수 있다.